version: '3'
networks: {rasa-network: {}}

services:

  chatbot:
    container_name: chatbot
    ports:
      - "5002:5002"
      - "5005:5005"
    volumes:
    - ./chatbot:/app/chatbot
    build:
      context: .
      dockerfile: docker/Dockerfile-chatbot
    command: ["rasa", "run", "--enable-api", "-p", "5003", "--cors", "*"]

  chatroom:
    container_name: chatroom
    ports:
      - "8080:8080"
    networks: ['rasa-network']
    volumes:
    - ./chatroom:/app/chatroom
    build:
      context: .
      dockerfile: docker/Dockerfile-chatroom
    command: ["sh","-c","yarn serve"]


